proof_id = ""
public_value = ""
public_owner = ""
asset_id = ""
num_input_notes = ""
input_note1_index = ""
input_note2_index = ""
input_note1 = []
input_note2 = []
output_note1 = []
output_note2 = []
partial_claim_note = []
signing_pub_key = []
signature = []
merkle_root = ""
input_path1 = []
input_path2 = []
account_note_index = ""
account_note_path = []
account_private_key = ""
alias_hash = ""
account_required = ""
backward_link = ""
allow_chain = ""
return = []
