global MAX_NUM_ASSETS_BIT_LENGTH = 30;

global DEFI_BRIDGE_ADDRESS_ID_LEN = 32;
// TODO add constant exprs so we can specify globals using other constants variables
global DEFI_BRIDGE_INPUT_A_ASSET_ID_LEN = 30;
global DEFI_BRIDGE_INPUT_B_ASSET_ID_LEN = 30;
global DEFI_BRIDGE_OUTPUT_A_ASSET_ID_LEN = 30;
global DEFI_BRIDGE_OUTPUT_B_ASSET_ID_LEN = 30;
global DEFI_BRIDGE_BITCONFIG_LEN = 32;
global DEFI_BRIDGE_AUX_DATA = 64;